#!/bin/bash
clear

## VAR
PROJECT_NAME="spider"

## BASH_MATIC
BASH_MATIC="${HOME}/.bashmatic"
[[ -s ${BASH_MATIC}/init.sh ]] || {
  rm -rf "${BASH_MATIC}" 2>/dev/null
  git clone https://github.com/kigster/bashmatic "${BASH_MATIC}" 2>&1 1>/dev/null
}
source "${BASH_MATIC}/init.sh"

divider.header() {
  h1.purple "The simple packages control manager in Arch Linux and another Unix similar system."
  IFS="|" read -r -a g_plus_plus_info <<< "$(g++ --version 2>&1 | tr '\n' '|')"
  h1 "${bldylw}G++" "${g_plus_plus_info[1]}" "${g_plus_plus_info[2]}" "${g_plus_plus_info[3]}" "${g_plus_plus_info[4]}"
  h1 "${bldylw}GIT:    ${bldblu}$(git --version)"
  h1 "${bldylw}CMAKE:  ${bldblu}$(cmake --version | tr '\n' ' ')"
}

divider.build() {
  hl.subtle "Build object file"

  run.set-next show-output-on
  run "bazel build main:${PROJECT_NAME}"
}

divider.run() {
  hl.subtle "Run project"

  run.set-next show-output-on
  run "bazel run main:${PROJECT_NAME}"
}

main() {
  divider.header
  divider.build
  divider.run
}
main